- name: Autenticar no Keycloak
  hosts: localhost
  gather_facts: no

  vars:
    keycloak_url: "https://dev-sso.dmcardapi.com.br"
    admin_username: "admin"
    admin_password: "aHT7dbw57M3MRFCC"
    realm_name: "TESTE-DEVOPS1"
    realm_display_name: "TESTE-DEVOPS1"

  tasks:
    - name: Autenticação no Keycloak
      uri:
        url: "{{ keycloak_url }}/realms/master/protocol/openid-connect/token"
        method: POST
        body_format: form-urlencoded
        body:
          grant_type: "password"
          username: "{{ admin_username }}"
          password: "{{ admin_password }}"
          client_id: "admin-cli"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        return_content: yes
      register: token_response

    - name: Mostrar token de acesso
      debug:
        var: token_response.json.access_token

    - name: Criação do Realm
      uri:
        url: "{{ keycloak_url }}/admin/realms"
        method: POST
        body_format: json
        body:
          realm: "{{ realm_name }}"
          displayName: "{{ realm_display_name }}"
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: "application/json"
        validate_certs: no

        