- name: Autenticar no Keycloak
  hosts: localhost
  gather_facts: no

  vars:
    keycloak_url: "https://dev-sso.dmcardapi.com.br/auth"
    admin_username: "admin"
    admin_password: "aHT7dbw57M3MRFCC"
    realm_name: "TESTE-DEVOPS"

  tasks:
    - name: Obter token de acesso
      get_url:
        url: "{{ keycloak_url }}/realms/master/protocol/openid-connect/token"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        data:
          grant_type: "password"
          client_id: "admin-cli"
          username: "{{ admin_username }}"
          password: "{{ admin_password }}"
        dest: token.json

    - name: Mostrar token de acesso
      debug:
        var: token.json.access_token