- name: Criar realm no Keycloak via REST API
  hosts: localhost
  vars:
    keycloak_host: "https://dev-sso.dmcardapi.com.br"
    keycloak_admin_username: "admin"
    keycloak_admin_password: "aHT7dbw57M3MRFCC"
    realm_name: "TESTE-DEVOPS"
    realm_enabled: true
    realm_display_name: "TESTE-DEVOPS"
  tasks:
    - name: Run a curl request to login and get jwt token
      command:  curl   -d 'client_id=admin-cli'   -d 'username=admin'   -d 'password=aHT7dbw57M3MRFCC'   -d grant_type=password   'https://dev-sso.dmcardapi.com.br/realms/master/protocol/openid-connect/token'
      register: (login_response|from_json).access_token

    - name: Print the jwt token
      debug:
        var: (login_response|from_json).access_token
