---
- name: Criar realm no Keycloak via REST API
  hosts: localhost
  vars:
    keycloak_host: "https://dev-sso.dmcardapi.com.br"
    keycloak_admin_username: "admin"
    keycloak_admin_password: "aHT7dbw57M3MRFCC"
    realm_name: "TESTE-DEVOPS"
    realm_enabled: true
    realm_display_name: "TESTE-DEVOPS"
  tasks:
- name: Obter token de acesso
  get_url:
    url: "http://{{ keycloak_host }}:{{ keycloak_port }}/auth/realms/{{ master_realm }}/protocol/openid-connect/token"
    method: POST
    headers:
      'Content-Type': 'application/x-www-form-urlencoded'
    validate_certs: no
    data:
      grant_type: password
      username: "{{ keycloak_admin_username }}"
      password: "{{ keycloak_admin_password }}"
  register: token_result
