- name: Criar realm no Keycloak via REST API
  hosts: localhost
  vars:
    keycloak_host: "https://dev-sso.dmcardapi.com.br"
    keycloak_admin_username: "admin"
    keycloak_admin_password: "aHT7dbw57M3MRFCC"
    realm_name: "TESTE-DEVOPS"
    realm_enabled: true
    realm_display_name: "TESTE-DEVOPS"
  tasks:
    - name: Authentication in Keycloak
      command:  curl   -d 'client_id=admin-cli'   -d 'username={{ keycloak_admin_username }}'   -d 'password={{ keycloak_admin_password }}'   -d grant_type=password   '{{ keycloak_host }}/realms/master/protocol/openid-connect/token'
      register: login_response

    - name: Print the jwt token
      debug:
        var: login_response.stdout
