- name: Criar realm no Keycloak via REST API
  hosts: localhost
  vars:
    keycloak_host: "dev-sso.dmcardapi.com.br"
    keycloak_admin_username: "admin"
    keycloak_admin_password: "aHT7dbw57M3MRFCC"
    realm_name: "TESTE-DEVOPS"
    realm_enabled: true
    realm_display_name: "TESTE-DEVOPS"
  tasks:
    - name: Criar realm
      uri:
        url: "https://{{ keycloak_host }}/realms/master/protocol/openid-connect/token"
        method: POST
        user: "{{ keycloak_admin_username }}"
        password: "{{ keycloak_admin_password }}"
        body_format: json
      register: response

    - name: Verificar resposta
      debug:
        var: response


