- name: Criar realm no Keycloak via REST API
  hosts: localhost
  vars:
    keycloak_host: "https://dev-sso.dmcardapi.com.br/auth"
    keycloak_admin_username: "admin"
    keycloak_admin_password: "aHT7dbw57M3MRFCC"
    realm_name: "TESTE-DEVOPS"
    realm_enabled: true
    realm_display_name: "TESTE-DEVOPS"
  tasks:
    - name: Create realm in Keycloak
      uri:
        url: "https://{{ keycloak_host }}/auth/admin/realms"
        method: POST
        user: "{{ keycloak_admin_username }}"
        password: "{{ keycloak_admin_password }}"
        force_basic_auth: yes
        validate_certs: no
        status_code: 201
        body_format: json
        body:
          realm: "{{ realm_name }}"
          enabled: true
      register: response

    - name: Print response
      debug:
        var: response