---
- name: Teste de login no Keycloak
  hosts: localhost
  gather_facts: no

  vars:
    keycloak_url: "https://exemplo.com/auth/realms/Exemplo"
    username: "seu_usuario"
    password: "sua_senha"

  tasks:
  - name: Fazer login no Keycloak
    uri:
      url: "{{ keycloak_url }}/protocol/openid-connect/token"
      method: POST
      body_format: json
      headers:
        Content-Type: "application/x-www-form-urlencoded"
      body:
        grant_type: "password"
        client_id: "nome_do_cliente"
        username: "{{ username }}"
        password: "{{ password }}"
      validate_certs: no
      status_code: 200
    register: resultado