- name: Autenticar e obter token de acesso do Keycloak
  hosts: localhost
  gather_facts: false

  vars:
    keycloak_url: "https://dev-sso.dmcardapi.com.br/admin/realms/master/protocol/openid-connect/token"

    username: "admin"
    password: "aHT7dbw57M3MRFCC"

  tasks:
    - name: Obter token de acesso
      get_url:
        url: "{{ keycloak_url }}"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        validate_certs: false
        data:
          grant_type: "password"
          username: "{{ username }}"
          password: "{{ password }}"
      register: response

    - name: Mostrar resposta
      debug:
        var: response.json()['access_token']