- name: Criar realm no Keycloak via REST API
  hosts: localhost
  vars:
    keycloak_host: "https://dev-sso.dmcardapi.com.br"
    keycloak_admin_username: "admin"
    keycloak_admin_password: "aHT7dbw57M3MRFCC"
    realm_name: "TESTE-DEVOPS"
    realm_enabled: true
    realm_display_name: "TESTE-DEVOPS"
  tasks:
    - name: Criar realm
      uri:
        url: "{{ keycloak_host }}/auth/realms/master/protocol/openid-connect/token"
        method: POST
        body_format: json
        body:
          client_id: admin-cli
          username: "{{ keycloak_admin_username }}"
          password: "{{ keycloak_admin_password }}"
          grant_type: password
        validate_certs: no
      register: keycloak_auth_result

    - name: Verificar resposta
      debug:
        var: keycloak_auth_result


