- name: Criar realm no Keycloak via REST API
  hosts: localhost
  vars:
    keycloak_url: "https://dev-sso.dmcardapi.com.br/auth"
    keycloak_admin_username: "admin"
    keycloak_admin_password: "aHT7dbw57M3MRFCC"
    realm_name: "TESTE-DEVOPS"
    realm_enabled: true
    realm_display_name: "TESTE-DEVOPS"
  tasks:
    - name: Obter token de acesso do administrador
      uri:
        url: "{{ keycloak_url }}/realms/master/protocol/openid-connect/token"
        method: POST
        body_format: json
        body:
          grant_type: "password"
          username: "{{ keycloak_admin_username }}"
          password: "{{ keycloak_admin_password }}"
          client_id: "admin-cli"
        validate_certs: false
        register: keycloak_token
    - name: Criar realm
      uri:
        url: "{{ keycloak_url }}/admin/realms"
        method: POST
        headers:
          Authorization: "Bearer {{ keycloak_token.json.access_token }}"
        body_format: json
        body:
          realm: "{{ realm_name }}"
          enabled: "{{ realm_enabled }}"
          displayName: "{{ realm_display_name }}"
        validate_certs: false
        status_code: 201