---

- hosts: cluster_k3s
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download

  
- hosts: master
  become: yes
  roles:
    - role: k3s_install/master_node
  
- hosts: node
  become: yes
  roles:
    - role: k3s_install/worker_node