---

- name: Copia K3S Servico
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Ativa Servico K3S
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
