---
- name: Copia serviço k3s
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Ativa k3s Service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
