---
- name: Copia serviço k3s
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Ativa k3s Service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Cria diretorio KUBECONFIG
  file:
    path: "{{ user }}/.kube"
    state: directory
    mode: '0755'

- name: Copia KUBECONFIG
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ user }}/.kube/config"
    owner: '{{ user }}'
    mode: '0644'