- name: Exemplo de tarefa usando credencial
  hosts: localhost
  tasks:
    - name: Tarefa que usa a credencial
      debug:
        msg: "Executando tarefa usando a credencial MyMachineCredential"
      vars:
        ansible_user: "{{ lookup( 'MyMachineCredential.username') }}"
        ansible_password: "{{ lookup( 'MyMachineCredential.password') }}"
