---
- name: Listar filas e enviar notificação para Teams
  hosts: localhost

  tasks:
    - name: Autenticar no RabbitMQ
      uri:
        url: "{{ rabbitmq_url }}/rabbitmq/api/queues"
        method: GET
        headers:
          Authorization: "Basic ({{ rabbitmq_user }}:{{ rabbitmq_passwd }} | | b64encode)"
        return_content: yes
      register: queues_response

    - name: Extrair nomes das filas
      set_fact:
        queue_names: "{{ queues_response.json | map(attribute='name') | list }}"
  
    - name: Exibir nomes das filas
      debug:
        var: queue_names
