- name: Exemplo de utilização de credentials
  hosts: localhost
  vars:
    rabbitmq_user: "{{ credentials['RabbitMQ Credentials'].username }}"
    rabbitmq_password: "{{ credentials['RabbitMQ Credentials'].password }}"
  tasks:
    - name: Exibir usuário e senha
      debug:
        msg: "Usuário: {{ rabbitmq_user }}, Senha: {{ rabbitmq_password }}"
