- name: Exemplo de utilização de credentials
  hosts: localhost
  vars:
    rabbitmq_user: "{{ lookup('cred', 'RabbitMQ Credentials').username }}"
    rabbitmq_password: "{{ lookup('cred', 'RabbitMQ Credentials').password }}"
  tasks:
    - name: Exibir usuário e senha
      debug:
        msg: "Usuário: {{ rabbitmq_user }}, Senha: {{ rabbitmq_password }}"
