- name: Exemplo de utilização de credentials
  hosts: localhost
  vars:
    rabbitmq_user: "{{ credentials_rabbitmq.username }}"
    rabbitmq_password: "{{ credentials_rabbitmq.password }}"
  tasks:
    - name: Exibir usuário e senha
      debug:
        msg: "Usuário: {{ rabbitmq_user }}, Senha: {{ rabbitmq_password }}"
