---
- name: Listar filas e enviar notificação para Teams
  hosts: localhost

  tasks:
    - name: Autenticar no RabbitMQ
      uri:
        url: https://direct-dev.dmcardapi.com.br/rabbitmq/api/queues
        method: GET
        headers:
          Authorization: "Basic {{ 'admin:aHT7dbw57M3MRFCC' | b64encode }}"
        return_content: yes
      register: queues_response

    - name: Extrair nomes das filas
      set_fact:
        queue_names: "{{ queues_response.json | map(attribute='name') | list }}"
