- hosts: ec2-instance
  become: yes
  vars:
    rabbitmq_user: admin
    rabbitmq_password: aHT7dbw57M3MRFCC
    rabbitmq_queues:
      - comp_cashin
      - comp_statement
      - create_device_token
      - create_device_token_delay
      - create_device_token_dlx
      - credit_analisys
      - credit_analisys_delay
      - credit_analisys_dlx
      - notification_http
      - notify_email
      - notify_push
      - notify_sms
      - pix_chargeback
      - pix_credit
      - pix_credit_description
      - ted_reversal
  tasks:
  - name: Instalar o RabbitMQ
    apt:
      name: rabbitmq-server
      state: present

  - name: Iniciar o serviço do RabbitMQ
    service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: Criação do usuário do RabbitMQ
    rabbitmq_user:
      user: "{{ rabbitmq_user }}"
      password: "{{ rabbitmq_password }}"
      tags: administrator
      vhost: /
      configure_priv: ".*"
      read_priv: ".*"
      write_priv: ".*"

  - name: Instalar plugin de console web do RabbitMQ
    rabbitmq_plugin:
      name: rabbitmq_management
      state: enabled

  - name: Reiniciar o serviço do RabbitMQ
    systemd:
      name: rabbitmq-server
      state: restarted


  - name: Reiniciar o serviço do RabbitMQ
    systemd:
      name: rabbitmq-server
      state: restarted

  - name: Criar filas no RabbitMQ
    rabbitmq_queue:
      login_user: "{{ rabbitmq_user }}"
      login_password: "{{ rabbitmq_password }}"
      vhost: /
      state: present
      name: "{{ item }}"
      durable: yes
      auto_delete: no
      arguments:
        x-queue-type: classic
    loop: "{{ rabbitmq_queues }}"
