- name: Exemplo de obtenção de informações da credential
  hosts: localhost
  tasks:
    - name: Obter informações da credential rabbitmq
      tower_credential_info:
        name: rabbitmq
      register: credential_info

    - name: Exibir informações da credential
      debug:
        msg: "Usuário: {{ credential_info.credential.username }}, Senha: {{ credential_info.credential.password }}"
