- name: Exemplo de obtenção de informações da credential
  hosts: localhost
  tasks:
    - name: Exibir informações da credential
      debug:
        msg: "Usuário: {{ rabbitmq_credential.username }}, Senha: {{ rabbitmq_credential.password }}"
  vars:
    rabbitmq_credential: "{{ lookup('awx_vault', 'rabbitmq_credential') }}"
