- hosts: 10.32.142.174
  become: yes
  vars:
    rabbitmq_user: admin
    rabbitmq_password: aHT7dbw57M3MRFCC
    rabbitmq_queues:
      - comp_cashin
      - comp_statement
      - create_device_token
      - create_device_token_delay
      - create_device_token_dlx
      - credit_analisys
      - credit_analisys_delay
      - credit_analisys_dlx
      - notification_http
      - notify_email
      - notify_push
      - notify_sms
      - pix_chargeback
      - pix_credit
      - pix_credit_description
      - ted_reversal
  tasks:
  - name: Instalar o RabbitMQ
    apt:
      name: rabbitmq-server
      state: present

  - name: Iniciar o serviço do RabbitMQ
    service:
      name: rabbitmq-server
      state: started
      enabled: yes
