---
- name: Listar filas no RabbitMQ
  hosts: localhost

  tasks:
    - name: Autenticar no RabbitMQ
      uri:
        url: https://direct-dev.dmcardapi.com.br/rabbitmq/api/queues
        method: GET
        headers:
          Authorization: "Basic {{ 'admin:aHT7dbw57M3MRFCC' | b64encode }}"
        return_content: yes
      register: response

    - name: Extrair nomes das filas
      set_fact:
        queue_names: "{{ response.json | map(attribute='name') | list }}"

    - name: Exibir nomes das filas
      debug:
        var: queue_names
