- name: Exemplo de utilização de credentials
  hosts: localhost
  vars:
    credential_name: "RabbitMQ Credentials"
  tasks:
    - name: Obter informações da credential
      awx.awx.awx_credential_info:
        name: "{{ credential_name }}"
      register: credential_info

    - name: Exibir usuário e senha
      debug:
        msg: "Usuário: {{ credential_info.credential.username }}, Senha: {{ credential_info.credential.password }}"
