- name: Exibir valores das variáveis
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Mostrar valor da variável 'user'
      debug:
        var: user

    - name: Mostrar valor da variável 'pass'
      debug:
        var: passwd
